name: ChunkBusters
main: com.i0dev.ChunkBusters.Heart
version: 1.0.0
author: i01
description: Place a chunk buster to destroy all blocks in a chunk.
website: https://i0dev.com/
softdepend:
  - Factions
  - PlaceHolderAPI
depend:
  - NBTAPI
commands:
  ChunkBusters:
    aliases:
      - chunkbuster
    description: The main command for ChunkBusters
    usage: /ChunkBusters <help/reload>
permissions:
  ChunkBusters.reload.cmd:
    description: Reload config
    default: op